---
- name: CF OCA | Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: true
  delegate_to: localhost

- name: CF OCA | Include OS family of {{ ansible_os_family }} variables.
  ansible.builtin.include_vars:
    file: "{{ item }}.yml"
  loop:
    - main
    - "{{ ansible_os_family }}"

- name: CF OCA | Setup config
  ansible.builtin.include_tasks: setup.yml

- name: CF OCA | Create certificate
  ansible.builtin.include_tasks: certificate.yml

- name: CF OCA | Configure with Nginx
  ansible.builtin.include_tasks: nginx.yml
